"""idempotency status and saga timezone columns

Revision ID: 8b3a9a15fb54
Revises: b5d1202b47a6
Create Date: 2026-04-25 14:40:38.623488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b3a9a15fb54'
down_revision: Union[str, Sequence[str], None] = 'b5d1202b47a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

order_idempotency_status_enum = sa.Enum(
    'PROCESSING',
    'SUCCEEDED',
    'FAILED',
    name='order_idempotency_status',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_creation_sagas', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('order_creation_sagas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_creation_sagas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    order_idempotency_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'order_idempotency_keys',
        sa.Column(
            'status',
            order_idempotency_status_enum,
            nullable=False,
            server_default='PROCESSING',
        ),
    )
    op.execute(
        """
        UPDATE order_idempotency_keys
        SET status = 'SUCCEEDED'
        WHERE response_body IS NOT NULL
        """
    )
    op.alter_column('order_idempotency_keys', 'status', server_default=None)
    op.add_column('order_idempotency_keys', sa.Column('error_code', sa.String(length=64), nullable=True))
    op.add_column('order_idempotency_keys', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_idempotency_keys', 'error_message')
    op.drop_column('order_idempotency_keys', 'error_code')
    op.drop_column('order_idempotency_keys', 'status')
    order_idempotency_status_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column('order_creation_sagas', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_creation_sagas', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_creation_sagas', 'next_retry_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
