"""order creation saga

Revision ID: b5d1202b47a6
Revises: 13d2fee951bf
Create Date: 2026-04-25 10:11:00.192950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d1202b47a6'
down_revision: Union[str, Sequence[str], None] = '13d2fee951bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_creation_sagas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('resolved_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_user_created', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('INIT', 'USER_CREATE_REQUESTED', 'USER_CREATED', 'ORDER_CREATED', 'COMPENSATION_PENDING', 'COMPENSATED', 'FAILED', name='order_creation_saga_status'), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_creation_sagas_idempotency_key'), 'order_creation_sagas', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_order_creation_sagas_request_fingerprint'), 'order_creation_sagas', ['request_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_creation_sagas_request_fingerprint'), table_name='order_creation_sagas')
    op.drop_index(op.f('ix_order_creation_sagas_idempotency_key'), table_name='order_creation_sagas')
    op.drop_table('order_creation_sagas')
    # ### end Alembic commands ###
